const CONFIG={chainIdHex:"0x89",TREASURY:"0x0000000000000000000000000000000000000000",TOKENS:{USDC:{symbol:"USDC",decimals:6,address:"0x0000000000000000000000000000000000000000"},USDT:{symbol:"USDT",decimals:6,address:"0x0000000000000000000000000000000000000000"}}};
const ERC20_ABI=["function transfer(address to,uint256 amount) returns (bool)"];
const $=id=>document.getElementById(id);let provider,signer,account;
const currencyByLang={en:"",ru:"≈ 92 ₽",es:"≈ 0.92 €",fr:"≈ 0.92 €",de:"≈ 0.92 €",zh:"≈ ¥7.25",ar:"≈ 3.67 د.إ",hi:"≈ ₹83",pt:"≈ R$5",tr:"≈ ₺32",id:"≈ Rp16,000",ja:"≈ ¥155",ko:"≈ ₩1,350"};
function langGuess(){const r=(navigator.language||"en").toLowerCase();for(const k of ["ru","es","fr","de","zh","ar","hi","pt","tr","id","ja","ko"])if(r.startsWith(k))return k;return"en"}
function applyLang(lang){const pack=window.I18N[lang]||window.I18N.en;document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.getAttribute("data-i18n");if(pack[k])el.textContent=pack[k]});$("localPrice").textContent=currencyByLang[lang]||"";localStorage.setItem("8b_lang",lang)}
function short(a){return a.slice(0,6)+"..."+a.slice(-4)}
async function connectWallet(){if(!window.ethereum){alert("MetaMask / Web3 wallet not found");return}provider=new ethers.BrowserProvider(window.ethereum);const accs=await provider.send("eth_requestAccounts",[]);account=accs[0];signer=await provider.getSigner();$("connectBtn").textContent=short(account);$("status").textContent="Connected: "+short(account)}
function units(){return Math.max(1,Number($("units").value||1))}
function updateTotal(){$("units").value=units();$("total").textContent="$"+units()}
async function pay(){if(!account){await connectWallet();return}if(CONFIG.TREASURY.includes("0000000000")){alert("Set TREASURY wallet in app.js before launch.");return}const t=CONFIG.TOKENS[$("token").value];if(t.address.includes("0000000000")){alert("Set token address in app.js before launch.");return}const contract=new ethers.Contract(t.address,ERC20_ABI,signer);const amount=ethers.parseUnits(String(units()),t.decimals);try{$("payBtn").textContent="Waiting...";const tx=await contract.transfer(CONFIG.TREASURY,amount);$("status").textContent="Transaction sent: "+tx.hash;await tx.wait();$("status").textContent="Confirmed: "+tx.hash;$("payBtn").textContent="Paid"}catch(e){console.error(e);$("payBtn").textContent=(window.I18N[$("langSelect").value]||window.I18N.en).pay;alert("Payment cancelled or failed.")}}
$("langSelect").addEventListener("change",e=>applyLang(e.target.value));$("connectBtn").addEventListener("click",connectWallet);$("joinBtn").addEventListener("click",()=>$("modal").classList.add("open"));$("closeModal").addEventListener("click",()=>$("modal").classList.remove("open"));$("modal").addEventListener("click",e=>{if(e.target.id==="modal")$("modal").classList.remove("open")});$("minus").addEventListener("click",()=>{$("units").value=Math.max(1,units()-1);updateTotal()});$("plus").addEventListener("click",()=>{$("units").value=units()+1;updateTotal()});$("units").addEventListener("input",updateTotal);$("payBtn").addEventListener("click",pay);$("treasuryText").textContent=CONFIG.TREASURY;const start=localStorage.getItem("8b_lang")||langGuess();$("langSelect").value=start;applyLang(start);updateTotal();